# Generated by Django 5.1.3 on 2024-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
